export const optionEstadosBrasil = [
    { id: 'opt-1', label: 'Acre (AC)', value: 'AC' },
    { id: 'opt-2', label: 'Alagoas (AL)', value: 'AL' },
    { id: 'opt-3', label: 'Amapá (AP)', value: 'AP' },
    { id: 'opt-4', label: 'Amazonas (AM)', value: 'AM' },
    { id: 'opt-5', label: 'Bahia (BA)', value: 'BA' },
    { id: 'opt-6', label: 'Ceará (CE)', value: 'CE' },
    { id: 'opt-7', label: 'Distrito Federal (DF)', value: 'DF' },
    { id: 'opt-8', label: 'Espírito Santo (ES)', value: 'ES' },
    { id: 'opt-9', label: 'Goiás (GO)', value: 'GO' },
    { id: 'opt-10', label: 'Maranhão (MA)', value: 'MA' },
    { id: 'opt-11', label: 'Mato Grosso (MT)', value: 'MT' },
    { id: 'opt-12', label: 'Mato Grosso do Sul (MS)', value: 'MS' },
    { id: 'opt-13', label: 'Minas Gerais (MG)', value: 'MG' },
    { id: 'opt-14', label: 'Pará (PA)', value: 'PA' },
    { id: 'opt-15', label: 'Paraíba (PB)', value: 'PB' },
    { id: 'opt-16', label: 'Paraná (PR)', value: 'PR' },
    { id: 'opt-17', label: 'Pernambuco (PE)', value: 'PE' },
    { id: 'opt-18', label: 'Piauí (PI)', value: 'PI' },
    { id: 'opt-19', label: 'Rio de Janeiro (RJ)', value: 'RJ' },
    { id: 'opt-20', label: 'Rio Grande do Norte (RN)', value: 'RN' },
    { id: 'opt-21', label: 'Rio Grande do Sul (RS)', value: 'RS' },
    { id: 'opt-22', label: 'Rondônia (RO)', value: 'RO' },
    { id: 'opt-23', label: 'Roraima (RR)', value: 'RR' },
    { id: 'opt-24', label: 'Santa Catarina (SC)', value: 'SC' },
    { id: 'opt-25', label: 'São Paulo (SP)', value: 'SP' },
    { id: 'opt-26', label: 'Sergipe (SE)', value: 'SE' },
    { id: 'opt-27', label: 'Tocantins (TO)', value: 'TO' },
];